version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_SHARED_BUFFERS: "128MB"
    networks:
      - app_network

  backend:
    build: ./url_shorter_backend
    container_name: url_shorter_backend
    env_file: ./url_shorter_backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    networks:
      - app_network

  frontend:
    build: ./url_shorter_frontend
    container_name: url_shorter_frontend
    env_file: ./url_shorter_frontend/.env.local
    ports:
      - "4173:80"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge