# Generated by Django 5.1.6 on 2025-02-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
